version: '3.7'

services:
  deployment-hub-ui:
    container_name: deployment-hub-ui
    build: https://github.com/jaredwines/deployment-hub.git#${DEPLOYMENT_HUB_BRANCH}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - /home/jared/Projects/deployment-hub-ui/.env